const activityRecords = [
  { id: "a1", group: "Today", time: "2:14 PM", type: "Call placed", action: "Outbound call", company: "Northstar Catering Co.", contact: "Elena Voss", rep: "Cole Brennan", channel: "Calls", result: "Completed", detail: "Walkthrough set for 2:00 PM.", leadId: "ns", phone: "(917) 555-0142", duration: "6m" },
  { id: "a2", group: "Today", time: "1:40 PM", type: "Email opened", action: "Opened approval letter", company: "Brightwell Dental Group", contact: "Dr. Priya Shah", rep: "Sam Ortiz", channel: "Email", result: "Opened", detail: "Approval letter · $160,000.", leadId: "bd", subject: "Approval letter" },
  { id: "a3", group: "Today", time: "1:05 PM", type: "SMS delivered", action: "Document request delivered", company: "Red Oak Auto Body", contact: "Dominic Ruiz", rep: "Sam Ortiz", channel: "SMS", result: "Delivered", detail: "Asked for a clean February statement.", leadId: "ro", phone: "(718) 555-0133" },
  { id: "a4", group: "Today", time: "12:20 PM", type: "Follow-up created", action: "Follow-up scheduled", company: "Harborline Logistics", contact: "Marcus Chen", rep: "Cole Brennan", channel: "CRM", result: "Scheduled", detail: "Call at 3:30 PM.", leadId: "hl" },
  { id: "a5", group: "Today", time: "11:12 AM", type: "Call missed", action: "Missed call", company: "Red Oak Auto Body", contact: "Dominic Ruiz", rep: "Sam Ortiz", channel: "Calls", result: "Missed", detail: "No answer on the office line.", leadId: "ro", phone: "(718) 555-0162" },
  { id: "a6", group: "Today", time: "10:04 AM", type: "Campaign started", action: "Started October New Leads", company: "Northstar Catering Co.", contact: "Elena Voss", rep: "Cole Brennan", channel: "Email", result: "Sending", detail: "Email campaign started.", campaign: "October New Leads" },
  { id: "a7", group: "Yesterday", time: "5:11 PM", type: "Email sent", action: "Term sheet sent", company: "Northstar Catering Co.", contact: "Elena Voss", rep: "Cole Brennan", channel: "Email", result: "Delivered", detail: "Term sheet · $125,000 second position.", leadId: "ns", subject: "Term sheet" },
  { id: "a8", group: "Yesterday", time: "4:12 PM", type: "Call missed", action: "No answer", company: "Red Oak Auto Body", contact: "Dominic Ruiz", rep: "Sam Ortiz", channel: "Calls", result: "No answer", detail: "Office line did not pick up.", leadId: "ro", phone: "(718) 555-0162" },
  { id: "a9", group: "Yesterday", time: "2:30 PM", type: "SMS replied", action: "Reply received", company: "Marlowe Wine Bar", contact: "Tess Marlowe", rep: "Cole Brennan", channel: "SMS", result: "Replied", detail: "Confirmed tomorrow's outline.", leadId: "mw" },
  { id: "a10", group: "Yesterday", time: "11:15 AM", type: "OCR completed", action: "March statement read", company: "Lumen & Co. Interiors", contact: "Sable Whitaker", rep: "Sam Ortiz", channel: "Scanner", result: "Completed", detail: "OCR finished. Deposits $79,200.", leadId: "lu" },
  { id: "a11", group: "Yesterday", time: "9:40 AM", type: "Lead status changed", action: "Approved", company: "Brightwell Dental Group", contact: "Dr. Priya Shah", rep: "Sam Ortiz", channel: "CRM", result: "Approved", detail: "In review → Approved.", leadId: "bd", from: "In review", to: "Approved" },
  { id: "a12", group: "Earlier", time: "Thu 4:10 PM", type: "Campaign completed", action: "NY Follow-up finished", company: "Keystone Pharmacy", contact: "Rahul Mehta", rep: "Cole Brennan", channel: "SMS", result: "Completed", detail: "SMS campaign completed.", campaign: "NY Follow-up" },
  { id: "a13", group: "Earlier", time: "Thu 1:20 PM", type: "WhatsApp delivered", action: "Intro delivered", company: "Atlas Peak HVAC", contact: "Jonah Hale", rep: "Jordan Hale", channel: "WhatsApp", result: "Delivered", detail: "WhatsApp intro delivered. Read not supplied.", leadId: "ap", phone: "(914) 555-0120" },
  { id: "a14", group: "Earlier", time: "Wed 3:05 PM", type: "Email bounced", action: "Bounce", company: "Harborline Logistics", contact: "Lina Chen", rep: "Alex Nguyen", channel: "Email", result: "Bounced", detail: "ops@ alias bounced.", leadId: "hl" },
  { id: "a15", group: "Earlier", time: "Wed 11:00 AM", type: "Lead assigned", action: "Assigned to Sam", company: "Lumen & Co. Interiors", contact: "Sable Whitaker", rep: "Sam Ortiz", channel: "CRM", result: "Assigned", detail: "Cole Brennan → Sam Ortiz.", leadId: "lu" },
  { id: "a16", group: "Earlier", time: "Tue 4:45 PM", type: "Extraction warning", action: "February unreadable", company: "Red Oak Auto Body", contact: "Dominic Ruiz", rep: "Sam Ortiz", channel: "Scanner", result: "Warning", detail: "Statement unreadable.", leadId: "ro" },
  { id: "a17", group: "Earlier", time: "Tue 9:12 AM", type: "SMS unsubscribed", action: "Stop received", company: "Atlas Peak HVAC", contact: "Jonah Hale", rep: "Jordan Hale", channel: "SMS", result: "Unsubscribed", detail: "Mobile only. Email still valid.", leadId: "ap", phone: "(914) 555-0120" },
  { id: "a18", group: "Earlier", time: "Mon 2:00 PM", type: "Note added", action: "Note added", company: "Keystone Pharmacy", contact: "Rahul Mehta", rep: "Cole Brennan", channel: "CRM", result: "Saved", detail: "Funded. First debit starts Monday.", leadId: "kp" }
];
const activityReps = ["Cole Brennan", "Sam Ortiz", "Jordan Hale", "Alex Nguyen"];
const activityState = { q: "", type: "all", channel: "all", reps: activityReps.slice(), company: "all", range: "all", result: "all", open: "" };
